name: Convert to PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Convert to pdf"
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          htmlFile: 'index.html'
          outputFile: 'resume.pdf'
          pdfOptions: '{"format": "A4", "printBackground": "true"}'
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: 'Resume file'
          path: 'resume.pdf'
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Release
#         uses: fnkr/github-action-ghr@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         env:
#           GHR_PATH: resume.pdf
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
