name: Convert to PDF

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: HTML to PDF
        uses: fifsky/html-to-pdf-action@v0.0.2
        with:
          htmlFile: 'index.html'
          outputFile: 'resume.pdf'
